version: "3"
services:
  web:
    build: .
    ports:
      - "8888:8888"
    environment:
        - SERVER_PORT=8888
        - MONGODB_URI=mongodb://db:27017/annotator
    links:
      - db
    depends_on:
      - db
  db:
    image: genomenexus/gn-mongo:latest
    restart: always
    ports:
      - "27017:27017"
